# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1ea1767b39bf6b8a282fc97b8d263ed"
name = "shopi-form"
application_url = "https://women-sand-extract-starting.trycloudflare.com"
embedded = true
handle = "shopi-form-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[app_proxy]
url = "https://women-sand-extract-starting.trycloudflare.com"
prefix = "apps"
subpath = "form"

[auth]
redirect_urls = ["https://women-sand-extract-starting.trycloudflare.com/auth/callback", "https://women-sand-extract-starting.trycloudflare.com/auth/shopify/callback", "https://women-sand-extract-starting.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
