# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1ea1767b39bf6b8a282fc97b8d263ed"
name = "shopi-form"
application_url = "https://td-herb-hiring-fragrances.trycloudflare.com"
embedded = true
handle = "shopi-form-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://td-herb-hiring-fragrances.trycloudflare.com/auth/callback", "https://td-herb-hiring-fragrances.trycloudflare.com/auth/shopify/callback", "https://td-herb-hiring-fragrances.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
