# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5103b6f46a88b161105429165d312aac"
name = "ShopiForm"
application_url = "https://phrases-pace-debt-equipped.trycloudflare.com"
embedded = true
handle = "shopiform-3"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://phrases-pace-debt-equipped.trycloudflare.com/auth/callback", "https://phrases-pace-debt-equipped.trycloudflare.com/auth/shopify/callback", "https://phrases-pace-debt-equipped.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
