# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d81145166b4c8ec861d79bbbe83741f9"
name = "ShopiForm"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customers,write_companies,write_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
